---
# tasks file for vault

- name: Create Vault system user
  user:
    state: present
    name: "{{ vault_user_name }}"
    comment: "{{ vault_user_gecos }}"
    system: yes
    password: '!'  # Disables user
    update_password: always

- name: Create Vault installation folder
  file:
    state: directory
    path: "{{ vault_installation_path }}"
    owner: "{{ vault_user_name }}"
    group: "{{ vault_user_gecos }}"
    mode: '0700'

- name: Install unzip to extract vault binary
  apt:
    state: present
    name: unzip
    update_cache: yes
    force_apt_get: yes

- name: Download and extract the Vault binary
  unarchive:
    src: "{{ vault_download_fullurl }}"
    dest: "{{ vualt_installation_path }}"
    remote_src: yes
    owner: "{{ vault_user_name }}"
    group: "{{ vault_user_name }}"
    mode: '0700'

- name: Symlink the Vault binary to a location within the PATH
  file:
    state: link
    src: "{{ vault_installation_path }}/vault"
    dest: "{{ vault_symlink_target }}"

- name: Configure Vault
  template:
    src: config.hcl
    dest: "{{ vault_installation_path }}/config.hcl"
    owner: "{{ vault_user_name }}"
    group: "{{ vault_user_name }}"
    mode: '0600'
  notify:
    - Restart Vault service

- name: Add systemd service
  template:
    src: vault.service
    dest: "/etc/systemd/system/vault.service"
    owner: root
    group: root
    mode: '0644'
  notify:
    - Reload systemd daemon

- name: Start and Enable Vault service
  systemd:
    state: started
    name: vault.service
    enabled: yes
