---
# generation of self-signed TLS certificates for vault

- name: Generate Vault private key
  openssl_privatekey:
    state: present
    path: /opt/vault/vault-key.pem
    size: 2048
    type: RSA
    owner: vault
    group: vault
    mode: '0600'

- name: Generate Vault public key
  openssl_publickey:
    state: present
    path: /opt/vault/vault-pub.pem
    privatekey_path: /opt/vault/vault-key.pem
    owner: vault
    group: vault
    mode: '0600'

- name: Generate CSR
  openssl_csr:
    state: present
    path: /opt/vault/vault-csr.pem
    privatekey_path: /opt/vault/vault-key.pem
    country_name: US
    state_or_province_name: New-York
    locality_name: Rochester
    organization_name: RITSEC
    organizational_unit_name: Operations Program
    common_name: vault.test.local
    owner: vault
    group: vault
    mode: '0600'

- name: Generate Vault certificate
  openssl_certificate:
    state: present
    path: /opt/vault/vault-cert.pem
    csr_path: /opt/vault/vault-csr.pem
    privatekey_path: /opt/vault/vault-key.pem
    provider: selfsigned
    owner: vault
    group: vault
    mode: '0600'