---
scenario:
  test_sequence:
    - lint
    - dependency
    - syntax
    - create
    - prepare
    - converge
    - idempotence
    - verify
    - cleanup
    - destroy

dependency:
  name: galaxy

driver:
  name: ec2

lint:
  name: yamllint

# All AMIs are in us-east-2
platforms:
  - name: ubuntu1804
    image: ami-021b7b04f1ac696c2

provisioner:
  name: ansible
  lint:
    name: ansible-lint
  playbooks:
    converge: ../resources/playbook.yml

verifier:
  name: testinfra
  lint:
    name: flake8
  options:
    v: true
  directory: ../resources/tests/
