---
scenario:
  # Defining a custom test sequence so things aren't unnecessarily created and
  # deleted.
  test_sequence:
    - lint
    - dependency
    - syntax
    - create
    - prepare
    - converge
    - idempotence
    - verify
    - cleanup
    - destroy

dependency:
  name: galaxy

driver:
  name: vagrant
  provider:
    name: virtualbox

lint:
  name: yamllint

platforms:
  - name: ubuntu1804
    box: ubuntu/bionic64
    memory: 2048
    cpus: 2

provisioner:
  name: ansible
  lint:
    name: ansible-lint
  playbooks:
    converge: ../resources/playbook.yml

verifier:
  name: testinfra
  lint:
    name: flake8
  options:
    v: true
  directory: ../resources/tests
